/**
 * alerts/engine.js
 * Threshold-based alert engine.
 * Evaluates incoming metrics and emits alerts when thresholds are crossed.
 */

const { v4: uuidv4 } = require('uuid');

// ─── Thresholds ───────────────────────────────────────────────
const THRESHOLDS = {
  cpu:         { warning: 80,  critical: 92  },
  ram:         { warning: 80,  critical: 93  },
  disk:        { warning: 80,  critical: 92  },
  temperature: { warning: 75,  critical: 85  },
  latency:     { warning: 100, critical: 300 },
};

// ─── Alert store (in-memory) ──────────────────────────────────
const alerts = [
  {
    id: uuidv4(), title: 'Mail Worker Service Down',
    message: 'mail-worker has been unreachable for 3 minutes. 7 restart attempts failed.',
    severity: 'critical', status: 'active', source: 'mail-worker',
    host: 'srv-master', metric: 'service',
    createdAt: new Date(Date.now() - 360_000).toISOString(),
    updatedAt: new Date(Date.now() - 60_000).toISOString(),
  },
  {
    id: uuidv4(), title: 'RabbitMQ Queue Depth High',
    message: 'Queue "events.fanout" depth: 4218 msgs. Consumer throughput below threshold.',
    severity: 'high', status: 'active', source: 'rabbitmq',
    host: 'srv-master', metric: 'queue_depth',
    createdAt: new Date(Date.now() - 720_000).toISOString(),
    updatedAt: new Date(Date.now() - 120_000).toISOString(),
  },
  {
    id: uuidv4(), title: 'PostgreSQL Slow Query Detected',
    message: 'Query execution >30s from user app_service. Possible missing index.',
    severity: 'medium', status: 'acknowledged', source: 'postgresql',
    host: 'srv-db-01', metric: 'db_latency', acknowledgedBy: 'dba-user',
    createdAt: new Date(Date.now() - 7_200_000).toISOString(),
    updatedAt: new Date(Date.now() - 1_800_000).toISOString(),
  },
];

// ─── Dedup: track which thresholds are already alerting ──────
const activeThresholdAlerts = new Map();

// ─── Evaluate a snapshot ─────────────────────────────────────
function evaluate(snapshot) {
  const newAlerts = [];

  // CPU
  checkThreshold('cpu_usage', snapshot.cpu?.usage, THRESHOLDS.cpu, 'system', 'localhost',
    `CPU usage at ${snapshot.cpu?.usage}% — threshold exceeded`, newAlerts);

  // RAM
  checkThreshold('ram_usage', snapshot.memory?.usage, THRESHOLDS.ram, 'system', 'localhost',
    `RAM usage at ${snapshot.memory?.usage}% — threshold exceeded`, newAlerts);

  // Disk (check each mount)
  snapshot.disks?.forEach(d => {
    checkThreshold(`disk_${d.mount}`, d.usage, THRESHOLDS.disk, 'system', 'localhost',
      `Disk ${d.mount} at ${d.usage}% — threshold exceeded`, newAlerts);
  });

  // CPU Temperature
  if (snapshot.cpu?.temperature) {
    checkThreshold('cpu_temp', snapshot.cpu.temperature, THRESHOLDS.temperature, 'system', 'localhost',
      `CPU temperature at ${snapshot.cpu.temperature}°C`, newAlerts);
  }

  // Push new alerts into store
  newAlerts.forEach(a => alerts.unshift(a));

  return newAlerts;
}

function checkThreshold(key, value, thresholds, source, host, msgBase, out) {
  if (value == null) return;
  let severity = null;
  if (value >= thresholds.critical) severity = 'critical';
  else if (value >= thresholds.warning) severity = 'high';

  if (severity) {
    const existing = activeThresholdAlerts.get(key);
    if (!existing) {
      const alert = {
        id: uuidv4(), title: msgBase, message: `${msgBase}. Auto-generated by threshold engine.`,
        severity, status: 'active', source, host, metric: key,
        createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
      };
      alerts.unshift(alert);
      activeThresholdAlerts.set(key, alert.id);
      out.push(alert);
    }
  } else {
    // Auto-resolve if back below threshold
    const existingId = activeThresholdAlerts.get(key);
    if (existingId) {
      const a = alerts.find(x => x.id === existingId);
      if (a && a.status === 'active') {
        a.status = 'resolved';
        a.updatedAt = new Date().toISOString();
      }
      activeThresholdAlerts.delete(key);
    }
  }
}

// ─── CRUD helpers ─────────────────────────────────────────────
const getAlerts   = (filters = {}) => {
  let result = [...alerts];
  if (filters.status)   result = result.filter(a => a.status === filters.status);
  if (filters.severity) result = result.filter(a => a.severity === filters.severity);
  return result.slice(0, 100);
};

const acknowledge = (id, user = 'admin') => {
  const a = alerts.find(x => x.id === id);
  if (a) { a.status = 'acknowledged'; a.acknowledgedBy = user; a.updatedAt = new Date().toISOString(); }
  return a;
};

const resolve = (id) => {
  const a = alerts.find(x => x.id === id);
  if (a) { a.status = 'resolved'; a.updatedAt = new Date().toISOString(); }
  return a;
};

module.exports = { evaluate, getAlerts, acknowledge, resolve, THRESHOLDS };
